In [4]:
!pip install nba_api
!pip install pandas

Requirement already satisfied: nba_api in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (1.1.13)
Requirement already satisfied: requests in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from nba_api) (2.28.1)
Requirement already satisfied: numpy in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from nba_api) (1.23.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from requests->nba_api) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from requests->nba_api) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from requests->nba_api) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from requests->nba_api) (3.4)
Requirement already satisfied: pandas in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (1.5.1)
Requirement already satisfied: pytz>=2020.1 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from pandas) (2022.5)
Requirement already satisfied: numpy>=1.20.3 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from pandas) (1.23.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/therealalex/anaconda3/envs/nba_venv/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [35]:
import pandas as pd
import os
from nba_api.stats.endpoints import playercareerstats,leaguedashptdefend,leaguedashptstats,leaguedashplayerbiostats,leaguehustlestatsplayer

path = os.getcwd()
parent = os.path.dirname(path)
DIR_DATA = parent+'/data/'

### Information about the NBA api parameters
- If season not specified, then it assumes the latest season is the
- If player or team parameter not specified, assumes team is the
- If season_type_all_star not specified, assumes Regular Season

In [6]:
carrer_defend = leaguedashptdefend.LeagueDashPtDefend(
                season = '2020-21',
                per_mode_simple='PerGame',
                defense_category='Overall',
                league_id = '00',
                season_type_all_star = 'Regular Season')

carrer_defend.get_data_frames()[0]

,CLOSE_DEF_PERSON_ID,PLAYER_NAME,PLAYER_LAST_TEAM_ID,PLAYER_LAST_TEAM_ABBREVIATION,PLAYER_POSITION,AGE,GP,G,FREQ,D_FGM,D_FGA,D_FG_PCT,NORMAL_FG_PCT,PCT_PLUSMINUS
0,203497,Rudy Gobert,1610612762,UTA,C,29.0,71,71,1.0,9.21,22.30,0.413,0.493,-0.079
1,201572,Brook Lopez,1610612749,MIL,C,33.0,69,69,1.0,8.96,19.80,0.452,0.489,-0.036
2,1627734,Domantas Sabonis,1610612754,IND,F-C,25.0,61,61,1.0,8.54,18.13,0.471,0.488,-0.017
3,203999,Nikola Jokic,1610612743,DEN,C,26.0,71,71,1.0,8.82,18.00,0.490,0.492,-0.002
4,1626167,Myles Turner,1610612754,IND,C-F,25.0,46,46,1.0,8.07,17.85,0.452,0.493,-0.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,1629033,Theo Pinson,1610612752,NYK,G-F,25.0,12,12,1.0,0.67,1.33,0.500,0.438,0.062
533,1629833,Keljin Blevins,1610612757,POR,G,25.0,14,14,1.0,0.43,1.29,0.333,0.417,-0.084
534,1630203,Grant Riller,1610612766,CHA,G,24.0,5,5,1.0,0.80,1.20,0.667,0.429,0.238
535,1630218,Robert Woodard II,1610612758,SAC,F,21.0,7,7,1.0,0.57,1.14,0.500,0.505,-0.005
536,204222,Greg Whittington,1610612743,DEN,F,28.0,1,1,1.0,0.00,1.00,0.000,0.407,-0.407

In [8]:
df_bio = leaguedashplayerbiostats.LeagueDashPlayerBioStats(
                season = '2020-21',
                per_mode_simple='PerGame',
                league_id = '00',
                season_type_all_star= 'Regular Season').get_data_frames()[0]
df_bio.head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,PLAYER_HEIGHT,PLAYER_HEIGHT_INCHES,PLAYER_WEIGHT,COLLEGE,COUNTRY,...,GP,PTS,REB,AST,NET_RATING,OREB_PCT,DREB_PCT,USG_PCT,TS_PCT,AST_PCT
0,203932,Aaron Gordon,1610612743,DEN,25.0,6-8,80,235,Arizona,USA,...,50,12.4,5.7,3.2,2.1,0.055,0.150,0.204,0.547,0.165
1,1628988,Aaron Holiday,1610612754,IND,24.0,6-0,72,185,UCLA,USA,...,66,7.2,1.3,1.9,-0.2,0.012,0.060,0.189,0.503,0.139
2,1630174,Aaron Nesmith,1610612738,BOS,21.0,6-5,77,215,Vanderbilt,USA,...,46,4.7,2.8,0.5,-0.5,0.041,0.146,0.133,0.573,0.047
3,1627846,Abdel Nader,1610612756,PHX,27.0,6-5,77,225,Iowa State,Egypt,...,24,6.7,2.6,0.8,5.0,0.020,0.151,0.183,0.605,0.078
4,1629690,Adam Mokoka,1610612741,CHI,22.0,6-4,76,190,None,France,...,14,1.1,0.4,0.4,-7.1,0.017,0.077,0.171,0.386,0.179

In [9]:
df_bio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PLAYER_ID             540 non-null    int64
 1   PLAYER_NAME           540 non-null    object
 2   TEAM_ID               540 non-null    int64
 3   TEAM_ABBREVIATION     540 non-null    object
 4   AGE                   540 non-null    float64
 5   PLAYER_HEIGHT         540 non-null    object
 6   PLAYER_HEIGHT_INCHES  540 non-null    int64
 7   PLAYER_WEIGHT         540 non-null    object
 8   COLLEGE               540 non-null    object
 9   COUNTRY               540 non-null    object
 10  DRAFT_YEAR            540 non-null    object
 11  DRAFT_ROUND           532 non-null    object
 12  DRAFT_NUMBER          531 non-null    object
 13  GP                    540 non-null    int64
 14  PTS                   540 non-null    float64
 15  REB                   540 non-null    float64
 16  AST                   540 non-null    float64
 17  NET_RATING            540 non-null    float64
 18  OREB_PCT              540 non-null    float64
 19  DREB_PCT              540 non-null    float64
 20  USG_PCT               540 non-null    float64
 21  TS_PCT                540 non-null    float64
 22  AST_PCT               540 non-null    float64
dtypes: float64(10), int64(4), object(9)
memory usage: 97.2+ KB

In [10]:
speed_distance_player = leaguedashptstats.LeagueDashPtStats(
                            season = '2019-20',
                            season_type_all_star = 'Regular Season',
                            per_mode_simple = 'PerGame',
                            player_or_team = 'Player',
                            # month = ,
                            )
speed_distance_player.get_data_frames()[0].head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,MIN1,DIST_FEET,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF,AVG_SPEED,AVG_SPEED_OFF,AVG_SPEED_DEF
0,203932,Aaron Gordon,1610612753,ORL,62,30,32,32.53,32.53,12820.23,2.43,1.34,1.08,4.20,4.65,3.76
1,1628988,Aaron Holiday,1610612754,IND,66,42,24,24.50,24.50,9661.73,1.83,0.96,0.87,4.20,4.42,3.98
2,1627846,Abdel Nader,1610612760,OKC,55,37,18,15.76,15.76,6444.60,1.22,0.64,0.58,4.32,4.55,4.09
3,1629690,Adam Mokoka,1610612741,CHI,11,3,8,10.15,10.15,4173.82,0.79,0.41,0.38,4.24,4.44,4.06
4,1629678,Admiral Schofield,1610612764,WAS,33,9,24,11.16,11.16,4341.64,0.82,0.44,0.38,4.19,4.59,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,203897,Zach LaVine,1610612741,CHI,60,20,40,34.76,34.76,14178.10,2.69,1.45,1.24,4.34,4.76,3.94
525,1629668,Zach Norvell Jr.,1610612744,GSW,5,2,3,8.16,8.16,3270.00,0.62,0.34,0.28,4.77,5.18,4.35
526,1629015,Zhaire Smith,1610612755,PHI,7,3,4,4.62,4.62,1945.71,0.37,0.19,0.18,4.27,4.20,4.34
527,1629627,Zion Williamson,1610612740,NOP,23,11,12,27.53,27.53,11307.00,2.14,1.13,1.01,4.39,4.85,3.95
528,1629597,Zylan Cheatham,1610612740,NOP,4,2,2,12.76,12.76,5550.50,1.05,0.56,0.49,4.54,4.88,4.23

In [39]:
hustle_player = leaguehustlestatsplayer.LeagueHustleStatsPlayer(
                            season = '2019-20',
                            season_type_all_star = 'Regular Season',
                            per_mode_time = 'PerGame',
                            # month = ,
                            )

hustle_player.get_data_frames()[0].head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,G,MIN,CONTESTED_SHOTS,CONTESTED_SHOTS_2PT,CONTESTED_SHOTS_3PT,...,PCT_LOOSE_BALLS_RECOVERED_DEF,OFF_BOXOUTS,DEF_BOXOUTS,BOX_OUTS,BOX_OUT_PLAYER_TEAM_REBS,BOX_OUT_PLAYER_REBS,PCT_BOX_OUTS_OFF,PCT_BOX_OUTS_DEF,PCT_BOX_OUTS_TEAM_REB,PCT_BOX_OUTS_REB
0,203932,Aaron Gordon,1610612753,ORL,24.0,62,32.5,5.32,3.37,1.95,...,0.507,0.23,0.85,1.08,0.63,0.34,0.209,0.791,0.929,0.500
1,1628988,Aaron Holiday,1610612754,IND,23.0,66,24.5,6.24,2.95,3.29,...,0.522,0.03,1.00,1.03,0.62,0.08,0.029,0.971,0.719,0.088
2,1627846,Abdel Nader,1610612760,OKC,26.0,55,15.8,4.05,2.31,1.75,...,0.586,0.00,0.78,0.78,0.38,0.11,0.000,1.000,0.750,0.214
3,1629690,Adam Mokoka,1610612741,CHI,21.0,11,10.2,1.27,0.36,0.91,...,0.333,0.27,0.55,0.82,0.36,0.18,0.333,0.667,1.000,0.500
4,1629678,Admiral Schofield,1610612764,WAS,23.0,33,11.2,2.48,1.55,0.94,...,0.444,0.03,1.12,1.15,0.45,0.12,0.026,0.974,0.833,0.222

In [40]:
hustle_player.get_data_frames()[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PLAYER_ID                      529 non-null    int64
 1   PLAYER_NAME                    529 non-null    object
 2   TEAM_ID                        529 non-null    int64
 3   TEAM_ABBREVIATION              529 non-null    object
 4   AGE                            529 non-null    float64
 5   G                              529 non-null    int64
 6   MIN                            529 non-null    float64
 7   CONTESTED_SHOTS                529 non-null    float64
 8   CONTESTED_SHOTS_2PT            529 non-null    float64
 9   CONTESTED_SHOTS_3PT            529 non-null    float64
 10  DEFLECTIONS                    529 non-null    float64
 11  CHARGES_DRAWN                  529 non-null    float64
 12  SCREEN_ASSISTS                 529 non-null    float64
 13  SCREEN_AST_PTS                 529 non-null    float64
 14  OFF_LOOSE_BALLS_RECOVERED      529 non-null    float64
 15  DEF_LOOSE_BALLS_RECOVERED      529 non-null    float64
 16  LOOSE_BALLS_RECOVERED          529 non-null    float64
 17  PCT_LOOSE_BALLS_RECOVERED_OFF  529 non-null    float64
 18  PCT_LOOSE_BALLS_RECOVERED_DEF  529 non-null    float64
 19  OFF_BOXOUTS                    529 non-null    float64
 20  DEF_BOXOUTS                    529 non-null    float64
 21  BOX_OUTS                       529 non-null    float64
 22  BOX_OUT_PLAYER_TEAM_REBS       529 non-null    float64
 23  BOX_OUT_PLAYER_REBS            529 non-null    float64
 24  PCT_BOX_OUTS_OFF               529 non-null    float64
 25  PCT_BOX_OUTS_DEF               529 non-null    float64
 26  PCT_BOX_OUTS_TEAM_REB          529 non-null    float64
 27  PCT_BOX_OUTS_REB               529 non-null    float64
dtypes: float64(23), int64(3), object(2)
memory usage: 115.8+ KB

## Data Aggreagtion

In [44]:
def get_df_player_data_season(season,league_id,season_segment):
    
    defend_data = leaguedashptdefend.LeagueDashPtDefend(
                season = season,
                per_mode_simple='PerGame',
                defense_category='Overall',
                league_id = league_id,
                season_type_all_star = season_segment).get_data_frames()[0]

    speed_distance_data = leaguedashptstats.LeagueDashPtStats(
                            season = season,
                            season_type_all_star = season_segment,
                            per_mode_simple = 'PerGame',
                            player_or_team = 'Player',
                            # month = ,
                            ).get_data_frames()[0]

    bio_data = leaguedashplayerbiostats.LeagueDashPlayerBioStats(
                season = season,
                per_mode_simple='PerGame',
                league_id = league_id,
                season_type_all_star= season_segment).get_data_frames()[0]

    touches_data = 0
    
    hustle_data = leaguehustlestatsplayer.LeagueHustleStatsPlayer(
                            season = '2019-20',
                            season_type_all_star = 'Regular Season',
                            per_mode_time = 'PerGame',
                            # month = ,
                            ).get_data_frames()[0]

    df_players = defend_data.copy()

    df_players = df_players.drop(columns = ['FREQ','G','PCT_PLUSMINUS','NORMAL_FG_PCT'])
    df_players = df_players.rename(columns = {'CLOSE_DEF_PERSON_ID':'PLAYER_ID','PLAYER_NAME':'name','PLAYER_POSITION':'position'})

    cols_to_merge = ['PLAYER_ID','PLAYER_HEIGHT','PLAYER_HEIGHT_INCHES','PLAYER_WEIGHT']

    df_players = df_players.merge(bio_data[cols_to_merge])
    
    cols_to_merge = ['PLAYER_ID','DIST_FEET','DIST_MILES','DIST_MILES_OFF','DIST_MILES_DEF','AVG_SPEED','AVG_SPEED_OFF','AVG_SPEED_DEF']

    df_players = df_players.merge(speed_distance_data[cols_to_merge])

    cols_to_merge = ['PLAYER_ID','CONTESTED_SHOTS','CONTESTED_SHOTS_2PT','CONTESTED_SHOTS_3PT','BOX_OUTS','OFF_BOXOUTS','DEF_BOXOUTS']

    df_players = df_players.merge(hustle_data[cols_to_merge])
    
    df_players = df_players.drop(columns = ['PLAYER_HEIGHT'])
    df_players = df_players.rename(columns ={'PLAYER_ID':'id','PLAYER_HEIGHT':'height', 'PLAYER_HEIGHT_INCHES': 'inches','PLAYER_WEIGHT':'weight'} )
    return df_players

#### Player Dataset Glossary
 - GP: Games played in segment
 - D_FGM: Defensive field goals made, like rebounds
 - D_FGA: Defensive field goals attemped
 - D_FG_PCT: Defensive field goals percentage
 - DIST_FEET: Total distance in feet made
 - DIST_MILES: Total distance in miles made
 - AVG_SPEED: speed of how many miles the player can run per second
 - inches: height in inches, which can be used to calculate in feet or cm

In [45]:
df_players = get_df_player_data_season('2019-20','00','Regular Season')
df_players

KeyError: "['CONTESTES_SHOTS_2PT'] not in index"

In [ ]:
df_injuries = pd.read_csv(DIR_DATA+'injuries_2010-2020.csv')
df_injuries.head()

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out inde...
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out ind...
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)

## Data processing

We are only going to focus on data from 2013-2014 season beyond, so injury data older than 2013 will be ignored.

In [ ]:
print(f'Number of rows: {df_injuries.shape[0]}')
regex_year = '2013-1[0-2]-(0[1-9]|[1-2][0-9]|3[0-1])|(201[4-9]|2020)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])'
df_injuries_processed = df_injuries[df_injuries['Date'].str.contains(regex_year)]
print(f'Number of rows: {df_injuries_processed.shape[0]}')
df_injuries_processed.head()

Number of rows: 27105
Number of rows: 19607

/tmp/ipykernel_24864/1822229384.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_injuries_processed = df_injuries[df_injuries['Date'].str.contains(regex_year)]

,Date,Team,Acquired,Relinquished,Notes
7498,2013-10-01,Thunder,NaN,Russell Westbrook,arthroscopic surgery on right knee (out indefi...
7499,2013-10-05,Blazers,NaN,C.J. McCollum,fractured bone in left foot (out indefinitely)
7500,2013-10-08,Hawks,NaN,Gustavo Ayon,strained right rotator cuff (out indefinitely)
7501,2013-10-10,Bobcats,NaN,Brendan Haywood,stress fracture in left foot (out indefinitely)
7502,2013-10-10,Mavericks,NaN,Brandan Wright,fractured left shoulder (surgery) (out indefin...